/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitaRouteImport } from './routes/vita'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as IndexRouteImport } from './routes/index'

const VitaRoute = VitaRouteImport.update({
  id: '/vita',
  path: '/vita',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commissions': typeof CommissionsRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/vita': typeof VitaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commissions': typeof CommissionsRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/vita': typeof VitaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commissions': typeof CommissionsRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/vita': typeof VitaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/commissions' | '/imprint' | '/privacy' | '/vita'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/commissions' | '/imprint' | '/privacy' | '/vita'
  id: '__root__' | '/' | '/commissions' | '/imprint' | '/privacy' | '/vita'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommissionsRoute: typeof CommissionsRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
  VitaRoute: typeof VitaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vita': {
      id: '/vita'
      path: '/vita'
      fullPath: '/vita'
      preLoaderRoute: typeof VitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommissionsRoute: CommissionsRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  VitaRoute: VitaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
